name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # It is required for GoReleaser to work properly
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      # - name: Cache Go modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y -q libgtk-3-dev libayatana-appindicator3-dev libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64
      - name: Install PCAP dependencies
        run: sudo apt-get install -y libpcap-dev

      - name: Install modules
        run: go mod tidy
      - name: Install GCC
        run: sudo apt install -y gcc-mingw-w64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
